source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.4'
# Use postgresql as the database for Active Record
gem 'pg'
# JSON
gem 'active_model_serializers'
# OmniAuth for Twitter
gem 'omniauth-twitter'

group :development, :test do
  gem 'sqlite3'
  # .env
  gem 'dotenv'
end

group :development do
  gem 'spring'
end
